class Constants {
  static List<List<String>> categoryData = [
    [
      'https://img.pngio.com/fruit-basket-png-png-collections-at-sccprecat-fruit-basket-png-800_800.png',
      'Fruits'
    ],
    [
      'https://4.imimg.com/data4/WA/BC/IMOB-34484009/c__data_users_defapps_appdata_internetexplorer_temp_sav-500x500.png',
      'Vegetables'
    ],
    [
      'https://4.imimg.com/data4/YI/XR/MY-26823497/branded-mrp-items-500x500.jpg',
      'Drinks'
    ],
    [
      'https://i2-prod.gloucestershirelive.co.uk/incoming/article2388909.ece/ALTERNATES/s615/1_Poundland-Promotion.jpg',
      'Household'
    ],
    [
      'https://5.imimg.com/data5/XU/DX/PV/SELLER-3277670/dry-fruits-500x500.jpg',
      'Dry Fruits'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy1'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy2'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy3'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy4'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy5'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy6'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy7'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy8'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy9'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy10'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy11'
    ],
    [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM8oE5gpw4fs_EdFLXESrR88AOx4y6a2SawQ&usqp=CAU',
      'Dummy12'
    ],
  ];
}
